<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            ['name' => 'Web Development'],
            ['name' => 'Mobile Application Development'],
            ['name' => 'Software Engineering'],
            ['name' => 'Database Management'],
            ['name' => 'Cybersecurity'],
            ['name' => 'Artificial Intelligence'],
            ['name' => 'Machine Learning'],
            ['name' => 'Cloud Computing'],
            ['name' => 'Blockchain Development'],
            ['name' => 'DevOps'],
            ['name' => 'Data Analysis'],
            ['name' => 'Big Data'],
            ['name' => 'Web Design'],
            ['name' => 'Game Development'],
            ['name' => 'Computer Vision'],
            ['name' => 'Data Visualization'],
            ['name' => 'UI/UX Design'],
            ['name' => 'Backend Development'],
            ['name' => 'Frontend Development'],
            ['name' => 'Software Testing'],
            ['name' => 'Virtualization'],
            ['name' => 'Quantum Computing'],
            ['name' => 'Embedded Systems'],
            ['name' => 'IT Support and Troubleshooting'],
            ['name' => 'Digital Marketing'],
            ['name' => 'Content Marketing'],
            ['name' => 'Search Engine Optimization (SEO)'],
            ['name' => 'Social Media Marketing'],
            ['name' => 'Pay-Per-Click (PPC) Advertising'],
            ['name' => 'Copywriting'],
            ['name' => 'Email Marketing'],
            ['name' => 'Conversion Rate Optimization (CRO)'],
            ['name' => 'Market Analysis'],
            ['name' => 'Influencer Marketing'],
            ['name' => 'Affiliate Marketing'],
            ['name' => 'Customer Relationship Management (CRM)'],
            ['name' => 'Brand Management'],
            ['name' => 'Google Ads'],
            ['name' => 'Marketing Automation'],
            ['name' => 'Public Relations'],
            ['name' => 'Social Media Management'],
            ['name' => 'Product Marketing'],
            ['name' => 'Event Planning'],
            ['name' => 'Competitive Analysis'],
            ['name' => 'Sales Enablement'],
            ['name' => 'Media Buying'],
            ['name' => 'Market Research'],
            ['name' => 'Curriculum Development'],
            ['name' => 'Online Teaching'],
            ['name' => 'Language Instruction'],
            ['name' => 'Educational Assessment'],
            ['name' => 'Student Counseling'],
            ['name' => 'Instructional Design'],
            ['name' => 'Educational Leadership'],
            ['name' => 'Learning Management System (LMS) Administration'],
            ['name' => 'Professional Development'],
            ['name' => 'Classroom Management'],
            ['name' => 'Instructional Coaching'],
            ['name' => 'Special Education'],
            ['name' => 'Test Preparation'],
            ['name' => 'E-learning Development'],
            ['name' => 'STEM Education'],
            ['name' => 'Mentoring'],
            ['name' => 'Self-Paced Learning Facilitation'],
            ['name' => 'Educational Technology Integration'],
            ['name' => 'Career Counseling'],
            ['name' => 'Educational Research'],
            ['name' => 'Graphic Design'],
            ['name' => 'Illustration'],
            ['name' => 'Photography'],
            ['name' => 'Video Production'],
            ['name' => 'Fashion Design'],
            ['name' => '3D Modeling'],
            ['name' => 'Animation'],
            ['name' => 'Interior Design'],
            ['name' => 'Logo Design'],
            ['name' => 'Typography'],
            ['name' => 'Calligraphy'],
            ['name' => 'Visual Merchandising'],
            ['name' => 'Jewelry Design'],
            ['name' => 'Print Design'],
            ['name' => 'Textile Design'],
            ['name' => 'Concept Art'],
            ['name' => 'Storyboarding'],
            ['name' => 'User Interface (UI) Design'],
            ['name' => 'Color Theory'],
            ['name' => 'Lighting Design'],
            ['name' => 'Project Management'],
            ['name' => 'Strategic Planning'],
            ['name' => 'Business Analysis'],
            ['name' => 'Product Management'],
            ['name' => 'Operations Management'],
            ['name' => 'Supply Chain Management'],
            ['name' => 'Leadership'],
            ['name' => 'Time Management'],
            ['name' => 'Conflict Resolution'],
            ['name' => 'Problem Solving'],
            ['name' => 'Sales Strategy'], // 101
            ['name' => 'Negotiation'], // 102
            ['name' => 'Customer Service'], // 103
            ['name' => 'Account Management'], // 104
            ['name' => 'Lead Generation'], // 105
            ['name' => 'Relationship Building'], // 106
            ['name' => 'Presentation Skills'], // 107
            ['name' => 'Sales Forecasting'], // 108
            ['name' => 'Market Segmentation'], // 109
            ['name' => 'Product Knowledge'], // 110
            ['name' => 'Sales Analytics'], // 111
            ['name' => 'Data Mining'], // 112
            ['name' => 'User Experience (UX) Research'], // 113
            ['name' => 'Behavioral Analysis'], // 114
            ['name' => 'Website Development'], // 115
            ['name' => 'Content Creation'], // 116
            ['name' => 'Content Management Systems (CMS)'], // 117
            ['name' => 'HTML/CSS'], // 118
            ['name' => 'JavaScript'], // 119
            ['name' => 'PHP'], // 120
            ['name' => 'Python'], // 121
            ['name' => 'Ruby on Rails'], // 122
            ['name' => 'Swift'], // 123
            ['name' => 'Kotlin'], // 124
            ['name' => 'C++'], // 125
            ['name' => 'C#'], // 126
            ['name' => 'Objective-C'], // 127
            ['name' => 'SQL'], // 128
            ['name' => 'NoSQL'], // 129
            ['name' => 'API Development'], // 130
            ['name' => 'RESTful Services'], // 131
            ['name' => 'GraphQL'], // 132
            ['name' => 'Software Architecture'], // 133
            ['name' => 'Agile Methodologies'], // 134
            ['name' => 'Scrum'], // 135
            ['name' => 'Kanban'], // 136
            ['name' => 'Git'], // 137
            ['name' => 'Version Control'], // 138
            ['name' => 'Continuous Integration'], // 139
            ['name' => 'Continuous Deployment'], // 140
            ['name' => 'Test-Driven Development (TDD)'], // 141
            ['name' => 'Behavior-Driven Development (BDD)'], // 142
            ['name' => 'Selenium'], // 143
            ['name' => 'JUnit'], // 144
            ['name' => 'Mobile UI Design'], // 145
            ['name' => 'User Interface (UI) Development'], // 146
            ['name' => 'Mobile Security'], // 147
            ['name' => 'Digital Product Management'], // 148
            ['name' => 'Software Documentation'], // 149
            ['name' => 'Open Source Contribution'], // 150
            ['name' => 'Technical Writing'], // 151
            ['name' => 'Cloud Architecture'], // 152
            ['name' => 'Microservices Architecture'], // 153
            ['name' => 'Containerization'], // 154
            ['name' => 'Docker'], // 155
            ['name' => 'Kubernetes'], // 156
            ['name' => 'AWS Services'], // 157
            ['name' => 'Google Cloud Platform (GCP)'], // 158
            ['name' => 'Microsoft Azure'], // 159
            ['name' => 'Network Security'], // 160
            ['name' => 'Firewall Management'], // 161
            ['name' => 'Penetration Testing'], // 162
            ['name' => 'Incident Response'], // 163
            ['name' => 'Vulnerability Assessment'], // 164
            ['name' => 'Risk Management'], // 165
            ['name' => 'Compliance Standards (ISO, GDPR)'], // 166
            ['name' => 'Data Protection'], // 167
            ['name' => 'Ethical Hacking'], // 168
            ['name' => 'Malware Analysis'], // 169
            ['name' => 'Digital Forensics'], // 170
            ['name' => 'Security Information and Event Management (SIEM)'], // 171
            ['name' => 'Data Governance'], // 172
            ['name' => 'Business Intelligence (BI)'], // 173
            ['name' => 'Predictive Analytics'], // 174
            ['name' => 'Statistical Analysis'], // 175
            ['name' => 'Data Warehousing'], // 176
            ['name' => 'ETL Processes'], // 177
            ['name' => 'Data Mining Techniques'], // 178
            ['name' => 'Artificial Neural Networks'], // 179
            ['name' => 'Natural Language Processing (NLP)'], // 180
            ['name' => 'Deep Learning'], // 181
            ['name' => 'Image Recognition'], // 182
            ['name' => 'Recommendation Systems'], // 183
            ['name' => 'Chatbot Development'], // 184
            ['name' => 'Robotics Process Automation (RPA)'], // 185
            ['name' => 'Digital Twins'], // 186
            ['name' => 'Augmented Reality (AR) Development'], // 187
            ['name' => 'Virtual Reality (VR) Development'], // 188
            ['name' => '3D Printing'], // 189
            ['name' => 'Embedded Software Development'], // 190
            ['name' => 'IoT (Internet of Things)'], // 191
            ['name' => 'Smart Home Technology'], // 192
            ['name' => 'Wearable Technology'], // 193
            ['name' => 'Health Tech Solutions'], // 194
            ['name' => 'Fintech Solutions'], // 195
            ['name' => 'E-commerce Development'], // 196
            ['name' => 'Social Media Strategy'], // 197
            ['name' => 'Community Management'], // 198
            ['name' => 'Crisis Communication'], // 199
            ['name' => 'Public Speaking'], // 200
            ['name' => 'Content Strategy'], // 201
            ['name' => 'SEO Optimization'], // 202
            ['name' => 'PPC Advertising'], // 203
            ['name' => 'Social Media Advertising'], // 204
            ['name' => 'Affiliate Marketing'], // 205
            ['name' => 'Brand Strategy'], // 206
            ['name' => 'Creative Direction'], // 207
            ['name' => 'Market Research'], // 208
            ['name' => 'Digital Marketing'], // 209
            ['name' => 'Email Marketing'], // 210
            ['name' => 'Copywriting'], // 211
            ['name' => 'Blogging'], // 212
            ['name' => 'Product Marketing'], // 213
            ['name' => 'Event Planning'], // 214
            ['name' => 'Lead Nurturing'], // 215
            ['name' => 'Customer Retention'], // 216
            ['name' => 'Customer Segmentation'], // 217
            ['name' => 'Digital Advertising'], // 218
            ['name' => 'Ad Copywriting'], // 219
            ['name' => 'Landing Page Optimization'], // 220
            ['name' => 'Brand Awareness'], // 221
            ['name' => 'Video Marketing'], // 222
            ['name' => 'Web Analytics'], // 223
            ['name' => 'Search Engine Marketing (SEM)'], // 224
            ['name' => 'Google Analytics'], // 225
            ['name' => 'Google Ads'], // 226
            ['name' => 'Bing Ads'], // 227
            ['name' => 'Facebook Ads'], // 228
            ['name' => 'Instagram Ads'], // 229
            ['name' => 'LinkedIn Ads'], // 230
            ['name' => 'Twitter Ads'], // 231
            ['name' => 'Pinterest Ads'], // 232
            ['name' => 'Snapchat Ads'], // 233
            ['name' => 'TikTok Ads'], // 234
            ['name' => 'Influencer Marketing'], // 235
            ['name' => 'Online Reputation Management'], // 236
            ['name' => 'Growth Hacking'], // 237
            ['name' => 'A/B Testing'], // 238
            ['name' => 'Conversion Rate Optimization (CRO)'], // 239
            ['name' => 'User Research'], // 240
            ['name' => 'Usability Testing'], // 241
            ['name' => 'Customer Journey Mapping'], // 242
            ['name' => 'Wireframing'], // 243
            ['name' => 'Prototyping'], // 244
            ['name' => 'Visual Design'], // 245
            ['name' => 'UX Writing'], // 246
            ['name' => 'Motion Design'], // 247
            ['name' => 'Interaction Design'], // 248
            ['name' => 'HTML5'], // 249
            ['name' => 'CSS3'], // 250
            ['name' => 'JavaScript Frameworks'], // 251
            ['name' => 'React.js'], // 252
            ['name' => 'Vue.js'], // 253
            ['name' => 'Angular'], // 254
            ['name' => 'Node.js'], // 255
            ['name' => 'Express.js'], // 256
            ['name' => 'MongoDB'], // 257
            ['name' => 'MySQL'], // 258
            ['name' => 'PostgreSQL'], // 259
            ['name' => 'Firebase'], // 260
            ['name' => 'Ruby on Rails Framework'], // 261
            ['name' => 'Laravel'], // 262
            ['name' => 'WordPress'], // 263
            ['name' => 'Joomla'], // 264
            ['name' => 'Drupal'], // 265
            ['name' => 'Shopify Development'], // 266
            ['name' => 'Magento'], // 267
            ['name' => 'Salesforce Development'], // 268
            ['name' => 'Microsoft Dynamics CRM'], // 269
            ['name' => 'HubSpot'], // 270
            ['name' => 'Zend Framework'], // 271
            ['name' => 'Django'], // 272
            ['name' => 'Flask'], // 273
            ['name' => 'Spring Boot'], // 274
            ['name' => 'Java Spring Framework'], // 275
            ['name' => 'DevOps'], // 276
            ['name' => 'Jenkins'], // 277
            ['name' => 'GitHub'], // 278
            ['name' => 'GitLab'], // 279
            ['name' => 'Bitbucket'], // 280
            ['name' => 'Docker Compose'], // 281
            ['name' => 'Terraform'], // 282
            ['name' => 'Ansible'], // 283
            ['name' => 'Chef'], // 284
            ['name' => 'Puppet'], // 285
            ['name' => 'Kubernetes Management'], // 286
            ['name' => 'Cloud Foundry'], // 287
            ['name' => 'AWS Lambda'], // 288
            ['name' => 'Google Cloud Functions'], // 289
            ['name' => 'Azure Functions'], // 290
            ['name' => 'Cloud Storage'], // 291
            ['name' => 'Google Drive API'], // 292
            ['name' => 'OneDrive API'], // 293
            ['name' => 'Dropbox API'], // 294
            ['name' => 'REST API Integration'], // 295
            ['name' => 'GraphQL API Integration'], // 296
            ['name' => 'Firebase Realtime Database'], // 297
            ['name' => 'Firestore Database'], // 298
            ['name' => 'WebSocket API'], // 299
            ['name' => 'OAuth'], // 300
            ['name' => 'Sales Strategies'], // 301
            ['name' => 'Account Management'], // 302
            ['name' => 'Sales Forecasting'], // 303
            ['name' => 'Negotiation Skills'], // 304
            ['name' => 'Business Development'], // 305
            ['name' => 'Customer Relationship Management'], // 306
            ['name' => 'Lead Generation'], // 307
            ['name' => 'Sales Presentations'], // 308
            ['name' => 'Sales Training'], // 309
            ['name' => 'Sales Reporting'], // 310
            ['name' => 'Cold Calling'], // 311
            ['name' => 'Market Analysis'], // 312
            ['name' => 'Market Penetration'], // 313
            ['name' => 'Channel Sales'], // 314
            ['name' => 'Product Knowledge'], // 315
            ['name' => 'Value Proposition'], // 316
            ['name' => 'Customer Service'], // 317
            ['name' => 'Consultative Selling'], // 318
            ['name' => 'B2B Sales'], // 319
            ['name' => 'B2C Sales'], // 320
            ['name' => 'Retail Sales'], // 321
            ['name' => 'Sales Operations'], // 322
            ['name' => 'Sales Analytics'], // 323
            ['name' => 'Sales Automation'], // 324
            ['name' => 'Client Retention'], // 325
            ['name' => 'Customer Acquisition'], // 326
            ['name' => 'Email Campaigns'], // 327
            ['name' => 'Client Negotiations'], // 328
            ['name' => 'Sales Targeting'], // 329
            ['name' => 'Upselling'], // 330
            ['name' => 'Cross-Selling'], // 331
            ['name' => 'Sales Funnel Management'], // 332
            ['name' => 'Sales Tracking Tools'], // 333
            ['name' => 'Salesforce Automation'], // 334
            ['name' => 'CRM Platforms'], // 335
            ['name' => 'Customer Data Analysis'], // 336
            ['name' => 'Target Market Research'], // 337
            ['name' => 'Sales Coaching'], // 338
            ['name' => 'Customer Engagement'], // 339
            ['name' => 'Sales Pipeline Management'], // 340
            ['name' => 'Sales Metrics'], // 341
            ['name' => 'Account Development'], // 342
            ['name' => 'Time Management'], // 343
            ['name' => 'Team Leadership'], // 344
            ['name' => 'Talent Acquisition'], // 345
            ['name' => 'Hiring Strategies'], // 346
            ['name' => 'Interviewing'], // 347
            ['name' => 'Employee Onboarding'], // 348
            ['name' => 'Employee Engagement'], // 349
            ['name' => 'Employee Retention'], // 350
            ['name' => 'Conflict Resolution'], // 351
            ['name' => 'Leadership Development'], // 352
            ['name' => 'Workforce Planning'], // 353
            ['name' => 'HR Analytics'], // 354
            ['name' => 'Succession Planning'], // 355
            ['name' => 'Training & Development'], // 356
            ['name' => 'Compensation Management'], // 357
            ['name' => 'Benefits Administration'], // 358
            ['name' => 'Payroll Processing'], // 359
            ['name' => 'Employee Relations'], // 360
            ['name' => 'Labor Law Compliance'], // 361
            ['name' => 'HR Software'], // 362
            ['name' => 'Performance Management'], // 363
            ['name' => 'Recruitment Strategies'], // 364
            ['name' => 'Diversity & Inclusion'], // 365
            ['name' => 'Employee Wellness'], // 366
            ['name' => 'Workplace Culture'], // 367
            ['name' => 'HR Policy Development'], // 368
            ['name' => 'Compensation Analysis'], // 369
            ['name' => 'Employee Feedback'], // 370
            ['name' => 'Labor Relations'], // 371
            ['name' => 'Change Management'], // 372
            ['name' => 'Employee Surveys'], // 373
            ['name' => 'HRIS Systems'], // 374
            ['name' => 'Team Collaboration'], // 375
            ['name' => 'Virtual Team Management'], // 376
            ['name' => 'Project Management'], // 377
            ['name' => 'Risk Management'], // 378
            ['name' => 'Crisis Management'], // 379
            ['name' => 'Agile Methodology'], // 380
            ['name' => 'Scrum'], // 381
            ['name' => 'Kanban'], // 382
            ['name' => 'Waterfall Model'], // 383
            ['name' => 'Project Scheduling'], // 384
            ['name' => 'Budget Management'], // 385
            ['name' => 'Resource Allocation'], // 386
            ['name' => 'Gantt Charts'], // 387
            ['name' => 'Project Documentation'], // 388
            ['name' => 'Risk Assessment'], // 389
            ['name' => 'Quality Assurance'], // 390
            ['name' => 'Cost Control'], // 391
            ['name' => 'Project Costing'], // 392
            ['name' => 'Project Scope Management'], // 393
            ['name' => 'Project Lifecycle Management'], // 394
            ['name' => 'Stakeholder Management'], // 395
            ['name' => 'Project Coordination'], // 396
            ['name' => 'Change Control'], // 397
            ['name' => 'Project Milestones'], // 398
            ['name' => 'Task Management'], // 399
            ['name' => 'Time Tracking'], // 400
            ['name' => 'Translation Skills'], // 401
            ['name' => 'Legal Translation'], // 402
            ['name' => 'Technical Translation'], // 403
            ['name' => 'Medical Translation'], // 404
            ['name' => 'Literary Translation'], // 405
            ['name' => 'Website Localization'], // 406
            ['name' => 'Simultaneous Translation'], // 407
            ['name' => 'Consecutive Translation'], // 408
            ['name' => 'Subtitling'], // 409
            ['name' => 'Transcription'], // 410
            ['name' => 'Proofreading in Translation'], // 411
            ['name' => 'Machine Translation'], // 412
            ['name' => 'CAT Tools (Computer-Assisted Translation)'], // 413
            ['name' => 'Terminology Management'], // 414
            ['name' => 'Bilingual Communication'], // 415
            ['name' => 'Cross-Cultural Communication'], // 416
            ['name' => 'Language Proficiency'], // 417
            ['name' => 'Accent Neutralization'], // 418
            ['name' => 'Multilingual Documentation'], // 419
            ['name' => 'Cultural Sensitivity in Translation'], // 420
            ['name' => 'Audiovisual Translation'], // 421
            ['name' => 'SEO for Multilingual Content'], // 422
            ['name' => 'Translation Project Management'], // 423
            ['name' => 'Language Teaching'], // 424
            ['name' => 'Interpretation for Conferences'], // 425
            ['name' => 'Transcreation'], // 426
            ['name' => 'Foreign Language Proofreading'], // 427
            ['name' => 'Literary Editing'], // 428
            ['name' => 'Translation for Subtitles'], // 429
            ['name' => 'Cultural Localization'], // 430
            ['name' => 'Localization Testing'], // 431
            ['name' => 'Documenting Translations'], // 432
            ['name' => 'Diplomatic Translation'], // 433
            ['name' => 'Ethnographic Research'], // 434
            ['name' => 'Translation for E-commerce'], // 435
            ['name' => 'Certified Translation'], // 436
            ['name' => 'Migration Laws and Regulations'], // 437
            ['name' => 'Immigration Law Knowledge'], // 438
            ['name' => 'Visa Processing'], // 439
            ['name' => 'Refugee and Asylum Seeker Assistance'], // 440
            ['name' => 'Resettlement Support'], // 441
            ['name' => 'Sponsorship Programs'], // 442
            ['name' => 'Cultural Integration Programs'], // 443
            ['name' => 'Community Outreach for Immigrants'], // 444
            ['name' => 'Public Policy for Immigrants'], // 445
            ['name' => 'International Relocation Services'], // 446
            ['name' => 'Resettlement Legal Services'], // 447
            ['name' => 'Language Learning for Immigrants'], // 448
            ['name' => 'Cross-Cultural Training'], // 449
            ['name' => 'Cultural Sensitivity Training'], // 450
            ['name' => 'Citizenship and Naturalization Assistance'], // 451
            ['name' => 'Work Visa Application'], // 452
            ['name' => 'Settlement Services'], // 453
            ['name' => 'Employment Services for Immigrants'], // 454
            ['name' => 'Family Reunification'], // 455
            ['name' => 'Job Search for Immigrants'], // 456
            ['name' => 'Interpreter Services for Immigrants'], // 457
            ['name' => 'Civic Integration Services'], // 458
            ['name' => 'Employment Rights for Migrants'], // 459
            ['name' => 'Assistance for Stateless People'], // 460
            ['name' => 'Asylum Application Support'], // 461
            ['name' => 'Refugee Protection Programs'], // 462
            ['name' => 'Social Services for Immigrants'], // 463
            ['name' => 'Health Services for Immigrants'], // 464
            ['name' => 'Housing Assistance for Immigrants'], // 465
            ['name' => 'Family and Marriage Counseling for Immigrants'], // 466
            ['name' => 'Cultural Mediation'], // 467
            ['name' => 'Humanitarian Aid Programs'], // 468
            ['name' => 'Human Rights Advocacy'], // 469
            ['name' => 'Human Trafficking Prevention'], // 470
            ['name' => 'Refugee Camp Management'], // 471
            ['name' => 'NGO Support for Refugees'], // 472
            ['name' => 'Foreign Policy on Immigration'], // 473
            ['name' => 'Immigrant Advocacy'], // 474
            ['name' => 'Relocation Planning for Immigrants'], // 475
            ['name' => 'Social Cohesion Programs'], // 476
            ['name' => 'Volunteering for Refugees'], // 477
            ['name' => 'Migration Research'], // 478
            ['name' => 'Transnational Networks'], // 479
            ['name' => 'Global Citizenship'], // 480
            ['name' => 'Cross-Border Education Programs'], // 481
            ['name' => 'Humanitarian Logistics'], // 482
            ['name' => 'Ethical Migration Advocacy'], // 483
            ['name' => 'Economic Integration of Migrants'], // 484
            ['name' => 'Multicultural Education'], // 485
            ['name' => 'Global Diaspora Networks'], // 486
            ['name' => 'International Education'], // 487
            ['name' => 'Public Relations for Immigrants'], // 488
            ['name' => 'Educational Programs for Refugees'], // 489
            ['name' => 'Healthcare Services for Refugees'], // 490
            ['name' => 'Public Health for Migrants'], // 491
            ['name' => 'Relocation and Resettlement Counseling'], // 492
            ['name' => 'Cultural Adaptation'], // 493
            ['name' => 'Language Access Programs'], // 494
            ['name' => 'Migration Policy Research'], // 495
            ['name' => 'Post-Resettlement Support'], // 496
            ['name' => 'Global Migration Trends'], // 497
            ['name' => 'International Student Support'], // 498
            ['name' => 'Internship Programs for Immigrants'], // 499
            ['name' => 'Temporary Protected Status Advocacy'], // 500
            ['name' => 'Agile Methodology'], // 501
            ['name' => 'Scrum Master'], // 502
            ['name' => 'Lean Manufacturing'], // 503
            ['name' => 'Kanban'], // 504
            ['name' => 'DevOps Practices'], // 505
            ['name' => 'Continuous Integration'], // 506
            ['name' => 'Continuous Deployment'], // 507
            ['name' => 'Software Testing'], // 508
            ['name' => 'Automated Testing'], // 509
            ['name' => 'Test-Driven Development'], // 510
            ['name' => 'Performance Testing'], // 511
            ['name' => 'Unit Testing'], // 512
            ['name' => 'Functional Testing'], // 513
            ['name' => 'Load Testing'], // 514
            ['name' => 'UI/UX Testing'], // 515
            ['name' => 'Security Testing'], // 516
            ['name' => 'Integration Testing'], // 517
            ['name' => 'Regression Testing'], // 518
            ['name' => 'API Testing'], // 519
            ['name' => 'Test Automation Frameworks'], // 520
            ['name' => 'Behavior-Driven Development'], // 521
            ['name' => 'Cypress Testing'], // 522
            ['name' => 'Selenium WebDriver'], // 523
            ['name' => 'Appium'], // 524
            ['name' => 'Jest Framework'], // 525
            ['name' => 'Jenkins'], // 526
            ['name' => 'GitLab CI/CD'], // 527
            ['name' => 'Docker'], // 528
            ['name' => 'Kubernetes'], // 529
            ['name' => 'Cloud Computing'], // 530
            ['name' => 'AWS (Amazon Web Services)'], // 531
            ['name' => 'Google Cloud Platform'], // 532
            ['name' => 'Microsoft Azure'], // 533
            ['name' => 'IBM Cloud'], // 534
            ['name' => 'Serverless Computing'], // 535
            ['name' => 'Virtualization'], // 536
            ['name' => 'Network Security'], // 537
            ['name' => 'Data Encryption'], // 538
            ['name' => 'Firewall Configuration'], // 539
            ['name' => 'Penetration Testing'], // 540
            ['name' => 'Incident Response'], // 541
            ['name' => 'Ethical Hacking'], // 542
            ['name' => 'Security Auditing'], // 543
            ['name' => 'Cybersecurity Risk Assessment'], // 544
            ['name' => 'Cloud Security'], // 545
            ['name' => 'Security Compliance'], // 546
            ['name' => 'Blockchain Technology'], // 547
            ['name' => 'Cryptocurrency'], // 548
            ['name' => 'Smart Contracts'], // 549
            ['name' => 'Decentralized Finance'], // 550
            ['name' => 'Web3 Development'], // 551
            ['name' => 'Ethereum Blockchain'], // 552
            ['name' => 'Bitcoin'], // 553
            ['name' => 'Solidity (Smart Contract Language)'], // 554
            ['name' => 'NFTs (Non-Fungible Tokens)'], // 555
            ['name' => 'Blockchain Security'], // 556
            ['name' => 'Cryptographic Algorithms'], // 557
            ['name' => 'IPFS (InterPlanetary File System)'], // 558
            ['name' => 'Supply Chain Management'], // 559
            ['name' => 'Logistics Management'], // 560
            ['name' => 'Inventory Management'], // 561
            ['name' => 'Procurement Management'], // 562
            ['name' => 'Warehouse Management'], // 563
            ['name' => 'Distribution Networks'], // 564
            ['name' => 'Fleet Management'], // 565
            ['name' => 'Retail Logistics'], // 566
            ['name' => 'Operations Research'], // 567
            ['name' => 'Route Optimization'], // 568
            ['name' => 'Demand Forecasting'], // 569
            ['name' => 'Business Continuity Planning'], // 570
            ['name' => 'Disaster Recovery Planning'], // 571
            ['name' => 'Crisis Management'], // 572
            ['name' => 'Business Process Outsourcing'], // 573
            ['name' => 'Enterprise Resource Planning (ERP)'], // 574
            ['name' => 'SAP Implementation'], // 575
            ['name' => 'Oracle ERP'], // 576
            ['name' => 'Microsoft Dynamics'], // 577
            ['name' => 'Supply Chain Automation'], // 578
            ['name' => 'Customer Relationship Management (CRM)'], // 579
            ['name' => 'Salesforce CRM'], // 580
            ['name' => 'Marketing Automation'], // 581
            ['name' => 'HubSpot'], // 582
            ['name' => 'Mailchimp'], // 583
            ['name' => 'Zoho CRM'], // 584
            ['name' => 'Customer Service Management'], // 585
            ['name' => 'Technical Support'], // 586
            ['name' => 'Helpdesk Systems'], // 587
            ['name' => 'Call Center Operations'], // 588
            ['name' => 'Ticketing Systems'], // 589
            ['name' => 'Customer Feedback Systems'], // 590
            ['name' => 'Sales Strategy'], // 591
            ['name' => 'Market Research'], // 592
            ['name' => 'Competitive Analysis'], // 593
            ['name' => 'Brand Management'], // 594
            ['name' => 'Product Management'], // 595
            ['name' => 'Product Development'], // 596
            ['name' => 'Go-To-Market Strategy'], // 597
            ['name' => 'Business Development'], // 598
            ['name' => 'Sales Operations'], // 599
            ['name' => 'Revenue Management'], // 600
            ['name' => 'Artificial Intelligence (AI)'], // 601
            ['name' => 'Machine Learning'], // 602
            ['name' => 'Natural Language Processing (NLP)'], // 603
            ['name' => 'Deep Learning'], // 604
            ['name' => 'Computer Vision'], // 605
            ['name' => 'Reinforcement Learning'], // 606
            ['name' => 'Neural Networks'], // 607
            ['name' => 'TensorFlow'], // 608
            ['name' => 'PyTorch'], // 609
            ['name' => 'Keras'], // 610
            ['name' => 'OpenCV'], // 611
            ['name' => 'Scikit-learn'], // 612
            ['name' => 'Data Preprocessing'], // 613
            ['name' => 'Supervised Learning'], // 614
            ['name' => 'Unsupervised Learning'], // 615
            ['name' => 'Data Science'], // 616
            ['name' => 'Big Data'], // 617
            ['name' => 'Data Visualization'], // 618
            ['name' => 'SQL Database'], // 619
            ['name' => 'NoSQL Database'], // 620
            ['name' => 'Data Mining'], // 621
            ['name' => 'Data Engineering'], // 622
            ['name' => 'Cloud Data Management'], // 623
            ['name' => 'Business Intelligence'], // 624
            ['name' => 'Tableau'], // 625
            ['name' => 'Power BI'], // 626
            ['name' => 'ETL Processes'], // 627
            ['name' => 'Hadoop'], // 628
            ['name' => 'Spark'], // 629
            ['name' => 'R Programming'], // 630
            ['name' => 'Python for Data Science'], // 631
            ['name' => 'AI Ethics'], // 632
            ['name' => 'Chatbots Development'], // 633
            ['name' => 'Voice Recognition'], // 634
            ['name' => 'Sentiment Analysis'], // 635
            ['name' => 'Recommendation Systems'], // 636
            ['name' => 'Computer Audition'], // 637
            ['name' => 'AI Algorithms'], // 638
            ['name' => 'Predictive Modeling'], // 639
            ['name' => 'AI Deployment'], // 640
            ['name' => 'Edge Computing'], // 641
            ['name' => 'Quantum Computing'], // 642
            ['name' => 'Blockchain Development'], // 643
            ['name' => 'Cryptography'], // 644
            ['name' => 'Smart Cities'], // 645
            ['name' => 'Internet of Things (IoT)'], // 646
            ['name' => 'Cloud Computing'], // 647
            ['name' => 'AWS Lambda'], // 648
            ['name' => 'Google Cloud Functions'], // 649
            ['name' => 'Microsoft Azure Functions'], // 650
            ['name' => 'Serverless Architecture'], // 651
            ['name' => 'Microservices Architecture'], // 652
            ['name' => 'API Development'], // 653
            ['name' => 'RESTful APIs'], // 654
            ['name' => 'GraphQL'], // 655
            ['name' => 'OAuth Authentication'], // 656
            ['name' => 'JWT Authentication'], // 657
            ['name' => 'WebSockets'], // 658
            ['name' => 'gRPC'], // 659
            ['name' => 'Docker Containers'], // 660
            ['name' => 'Kubernetes Cluster Management'], // 661
            ['name' => 'CI/CD Pipeline'], // 662
            ['name' => 'GitHub Actions'], // 663
            ['name' => 'GitLab CI'], // 664
            ['name' => 'Jenkins CI'], // 665
            ['name' => 'Ansible'], // 666
            ['name' => 'Terraform'], // 667
            ['name' => 'Chef'], // 668
            ['name' => 'Puppet'], // 669
            ['name' => 'Vagrant'], // 670
            ['name' => 'DevOps Tools'], // 671
            ['name' => 'Linux Administration'], // 672
            ['name' => 'Windows Server Administration'], // 673
            ['name' => 'Network Configuration'], // 674
            ['name' => 'Virtual Machines'], // 675
            ['name' => 'Cloud Security'], // 676
            ['name' => 'Identity and Access Management'], // 677
            ['name' => 'Encryption Techniques'], // 678
            ['name' => 'Firewall Setup'], // 679
            ['name' => 'Penetration Testing'], // 680
            ['name' => 'Ethical Hacking'], // 681
            ['name' => 'Social Engineering'], // 682
            ['name' => 'Malware Analysis'], // 683
            ['name' => 'Red Teaming'], // 684
            ['name' => 'Blue Teaming'], // 685
            ['name' => 'Security Auditing'], // 686
            ['name' => 'Compliance Audits'], // 687
            ['name' => 'Incident Management'], // 688
            ['name' => 'Risk Assessment'], // 689
            ['name' => 'Business Continuity'], // 690
            ['name' => 'Disaster Recovery'], // 691
            ['name' => 'Data Backup Strategies'], // 692
            ['name' => 'Data Loss Prevention'], // 693
            ['name' => 'Cyber Security Policies'], // 694
            ['name' => 'Governance Risk and Compliance'], // 695
            ['name' => 'Web Application Security'], // 696
            ['name' => 'Mobile Application Security'], // 697
            ['name' => 'Identity Protection'], // 698
            ['name' => 'Network Monitoring'], // 699
            ['name' => 'Log Analysis'], // 700
            ['name' => 'Agile Methodology'], // 701
            ['name' => 'Scrum Framework'], // 702
            ['name' => 'Kanban'], // 703
            ['name' => 'Lean Management'], // 704
            ['name' => 'DevOps Culture'], // 705
            ['name' => 'Continuous Integration (CI)'], // 706
            ['name' => 'Continuous Delivery (CD)'], // 707
            ['name' => 'Unit Testing'], // 708
            ['name' => 'Test Automation'], // 709
            ['name' => 'Behavior-Driven Development (BDD)'], // 710
            ['name' => 'Acceptance Test-Driven Development (ATDD)'], // 711
            ['name' => 'TDD (Test-Driven Development)'], // 712
            ['name' => 'Software Testing'], // 713
            ['name' => 'Quality Assurance'], // 714
            ['name' => 'Load Testing'], // 715
            ['name' => 'Performance Testing'], // 716
            ['name' => 'Usability Testing'], // 717
            ['name' => 'Security Testing'], // 718
            ['name' => 'Cross-Browser Testing'], // 719
            ['name' => 'Regression Testing'], // 720
            ['name' => 'Acceptance Testing'], // 721
            ['name' => 'Exploratory Testing'], // 722
            ['name' => 'Automated Testing Frameworks'], // 723
            ['name' => 'Selenium'], // 724
            ['name' => 'JUnit'], // 725
            ['name' => 'TestNG'], // 726
            ['name' => 'Appium'], // 727
            ['name' => 'Postman'], // 728
            ['name' => 'Swagger'], // 729
            ['name' => 'JUnit5'], // 730
            ['name' => 'Mockito'], // 731
            ['name' => 'Jest'], // 732
            ['name' => 'Cypress'], // 733
            ['name' => 'JUnit4'], // 734
            ['name' => 'SoapUI'], // 735
            ['name' => 'Charles Proxy'], // 736
            ['name' => 'Fiddler'], // 737
            ['name' => 'TestComplete'], // 738
            ['name' => 'Jenkins Pipeline'], // 739
            ['name' => 'SonarQube'], // 740
            ['name' => 'GitFlow'], // 741
            ['name' => 'Docker Compose'], // 742
            ['name' => 'Kubernetes Helm'], // 743
            ['name' => 'Terraform Configuration'], // 744
            ['name' => 'CloudFormation'], // 745
            ['name' => 'Jira'], // 746
            ['name' => 'Trello'], // 747
            ['name' => 'Asana'], // 748
            ['name' => 'Slack'], // 749
            ['name' => 'Notion'], // 750
            ['name' => 'Confluence'], // 751
            ['name' => 'Basecamp'], // 752
            ['name' => 'Microsoft Teams'], // 753
            ['name' => 'Google Workspace'], // 754
            ['name' => 'Zoom'], // 755
            ['name' => 'Cisco WebEx'], // 756
            ['name' => 'Miro'], // 757
            ['name' => 'Lucidchart'], // 758
            ['name' => 'Monday.com'], // 759
            ['name' => 'Airtable'], // 760
            ['name' => 'Workday'], // 761
            ['name' => 'Salesforce CRM'], // 762
            ['name' => 'HubSpot CRM'], // 763
            ['name' => 'Zoho CRM'], // 764
            ['name' => 'Pipedrive'], // 765
            ['name' => 'Freshsales'], // 766
            ['name' => 'Marketo'], // 767
            ['name' => 'Mailchimp'], // 768
            ['name' => 'Intercom'], // 769
            ['name' => 'Zendesk'], // 770
            ['name' => 'Help Scout'], // 771
            ['name' => 'SurveyMonkey'], // 772
            ['name' => 'Typeform'], // 773
            ['name' => 'Qualtrics'], // 774
            ['name' => 'Google Analytics'], // 775
            ['name' => 'Adobe Analytics'], // 776
            ['name' => 'Tableau Software'], // 777
            ['name' => 'Power BI Desktop'], // 778
            ['name' => 'SQL Server Reporting Services'], // 779
            ['name' => 'Google Tag Manager'], // 780
            ['name' => 'Kissmetrics'], // 781
            ['name' => 'HubSpot Marketing Hub'], // 782
            ['name' => 'Hotjar'], // 783
            ['name' => 'Crazy Egg'], // 784
            ['name' => 'Unbounce'], // 785
            ['name' => 'Leadpages'], // 786
            ['name' => 'Optimizely'], // 787
            ['name' => 'VWO (Visual Website Optimizer)'], // 788
            ['name' => 'Evernote'], // 789
            ['name' => 'Google Keep'], // 790
            ['name' => 'OneNote'], // 791
            ['name' => 'Trello Board Management'], // 792
            ['name' => 'Dropbox'], // 793
            ['name' => 'Google Drive'], // 794
            ['name' => 'Microsoft OneDrive'], // 795
            ['name' => 'Box.com'], // 796
            ['name' => 'iCloud'], // 797
            ['name' => 'FTP/SFTP'], // 798
            ['name' => 'GitHub'], // 799
            ['name' => 'GitLab'], // 800
            ['name' => 'Artificial Intelligence (AI)'], // 801
            ['name' => 'Machine Learning'], // 802
            ['name' => 'Deep Learning'], // 803
            ['name' => 'Natural Language Processing (NLP)'], // 804
            ['name' => 'Computer Vision'], // 805
            ['name' => 'Reinforcement Learning'], // 806
            ['name' => 'Supervised Learning'], // 807
            ['name' => 'Unsupervised Learning'], // 808
            ['name' => 'TensorFlow'], // 809
            ['name' => 'PyTorch'], // 810
            ['name' => 'Keras'], // 811
            ['name' => 'OpenCV'], // 812
            ['name' => 'Scikit-Learn'], // 813
            ['name' => 'ML Algorithms'], // 814
            ['name' => 'Neural Networks'], // 815
            ['name' => 'Chatbots'], // 816
            ['name' => 'Voice Recognition'], // 817
            ['name' => 'Recommender Systems'], // 818
            ['name' => 'Data Mining'], // 819
            ['name' => 'Data Visualization'], // 820
            ['name' => 'Predictive Analytics'], // 821
            ['name' => 'Big Data Analytics'], // 822
            ['name' => 'Data Cleaning'], // 823
            ['name' => 'Data Transformation'], // 824
            ['name' => 'Data Wrangling'], // 825
            ['name' => 'Business Intelligence'], // 826
            ['name' => 'SQL Database Management'], // 827
            ['name' => 'NoSQL Database'], // 828
            ['name' => 'Data Warehousing'], // 829
            ['name' => 'Data Modeling'], // 830
            ['name' => 'ETL (Extract, Transform, Load)'], // 831
            ['name' => 'Tableau'], // 832
            ['name' => 'Power BI'], // 833
            ['name' => 'Google Data Studio'], // 834
            ['name' => 'QlikView'], // 835
            ['name' => 'Domo'], // 836
            ['name' => 'Looker'], // 837
            ['name' => 'Apache Hadoop'], // 838
            ['name' => 'Apache Spark'], // 839
            ['name' => 'Apache Kafka'], // 840
            ['name' => 'MongoDB'], // 841
            ['name' => 'Cassandra'], // 842
            ['name' => 'Redis'], // 843
            ['name' => 'Elasticsearch'], // 844
            ['name' => 'SQLite'], // 845
            ['name' => 'PostgreSQL'], // 846
            ['name' => 'MySQL'], // 847
            ['name' => 'GraphQL'], // 848
            ['name' => 'RESTful APIs'], // 849
            ['name' => 'SOAP APIs'], // 850
            ['name' => 'Web Scraping'], // 851
            ['name' => 'Automated Web Testing'], // 852
            ['name' => 'Jupyter Notebooks'], // 853
            ['name' => 'Google Cloud Platform (GCP)'], // 854
            ['name' => 'Amazon Web Services (AWS)'], // 855
            ['name' => 'Microsoft Azure'], // 856
            ['name' => 'Docker'], // 857
            ['name' => 'Kubernetes'], // 858
            ['name' => 'CI/CD Pipelines'], // 859
            ['name' => 'Serverless Computing'], // 860
            ['name' => 'Cloud Security'], // 861
            ['name' => 'Cloud Storage'], // 862
            ['name' => 'Cloud Databases'], // 863
            ['name' => 'AWS Lambda'], // 864
            ['name' => 'AWS S3'], // 865
            ['name' => 'Terraform'], // 866
            ['name' => 'Google Kubernetes Engine (GKE)'], // 867
            ['name' => 'Azure Kubernetes Service (AKS)'], // 868
            ['name' => 'Infrastructure as Code (IaC)'], // 869
            ['name' => 'Virtualization'], // 870
            ['name' => 'VMware'], // 871
            ['name' => 'VirtualBox'], // 872
            ['name' => 'Hyper-V'], // 873
            ['name' => 'Network Security'], // 874
            ['name' => 'Firewall Configuration'], // 875
            ['name' => 'VPN Setup'], // 876
            ['name' => 'Penetration Testing'], // 877
            ['name' => 'Ethical Hacking'], // 878
            ['name' => 'Cybersecurity Awareness'], // 879
            ['name' => 'Cryptography'], // 880
            ['name' => 'SSL/TLS'], // 881
            ['name' => 'Two-Factor Authentication'], // 882
            ['name' => 'Intrusion Detection Systems'], // 883
            ['name' => 'Zero Trust Security'], // 884
            ['name' => 'Social Engineering Awareness'], // 885
            ['name' => 'SQL Injection Prevention'], // 886
            ['name' => 'Malware Analysis'], // 887
            ['name' => 'Anti-Virus Software'], // 888
            ['name' => 'Firewalls'], // 889
            ['name' => 'Identity and Access Management (IAM)'], // 890
            ['name' => 'Information Security Management Systems (ISMS)'], // 891
            ['name' => 'PCI-DSS Compliance'], // 892
            ['name' => 'GDPR Compliance'], // 893
            ['name' => 'ISO 27001 Certification'], // 894
            ['name' => 'Risk Assessment'], // 895
            ['name' => 'Vulnerability Management'], // 896
            ['name' => 'Incident Response'], // 897
            ['name' => 'Disaster Recovery'], // 898
            ['name' => 'Business Continuity Planning'], // 899
            ['name' => 'Data Loss Prevention (DLP)'], // 900
            ['name' => 'Translation Services'], // 901
            ['name' => 'Localization'], // 902
            ['name' => 'Subtitling'], // 903
            ['name' => 'Transcription'], // 904
            ['name' => 'Language Interpretation'], // 905
            ['name' => 'Cultural Adaptation'], // 906
            ['name' => 'Proofreading'], // 907
            ['name' => 'Multilingual Communication'], // 908
            ['name' => 'Bilingual Customer Support'], // 909
            ['name' => 'Multilingual Content Writing'], // 910
            ['name' => 'Language Dubbing'], // 911
            ['name' => 'Audio Transcription'], // 912
            ['name' => 'Simultaneous Interpretation'], // 913
            ['name' => 'Document Translation'], // 914
            ['name' => 'Text-to-Speech Conversion'], // 915
            ['name' => 'Language Training'], // 916
            ['name' => 'E-learning Content Development'], // 917
            ['name' => 'Voice Over Services'], // 918
            ['name' => 'SEO Content Writing'], // 919
            ['name' => 'Copywriting'], // 920
            ['name' => 'Content Strategy'], // 921
            ['name' => 'Content Marketing'], // 922
            ['name' => 'Blog Writing'], // 923
            ['name' => 'Content Editing'], // 924
            ['name' => 'Creative Writing'], // 925
            ['name' => 'Technical Writing'], // 926
            ['name' => 'Journalism'], // 927
            ['name' => 'Press Release Writing'], // 928
            ['name' => 'Product Descriptions'], // 929
            ['name' => 'Academic Writing'], // 930
            ['name' => 'Grant Writing'], // 931
            ['name' => 'Business Writing'], // 932
            ['name' => 'Report Writing'], // 933
            ['name' => 'Speech Writing'], // 934
            ['name' => 'Case Study Writing'], // 935
            ['name' => 'Whitepapers'], // 936
            ['name' => 'Product Manuals'], // 937
            ['name' => 'Website Content Writing'], // 938
            ['name' => 'Ad Copywriting'], // 939
            ['name' => 'Video Script Writing'], // 940
            ['name' => 'User Manuals'], // 941
            ['name' => 'Public Relations'], // 942
            ['name' => 'Social Media Management'], // 943
            ['name' => 'Branding'], // 944
            ['name' => 'Corporate Communications'], // 945
            ['name' => 'Event Planning'], // 946
            ['name' => 'Marketing Communications'], // 947
            ['name' => 'Email Marketing'], // 948
            ['name' => 'Social Media Advertising'], // 949
            ['name' => 'Community Management'], // 950
            ['name' => 'Influencer Marketing'], // 951
            ['name' => 'Affiliate Marketing'], // 952
            ['name' => 'Retail Marketing'], // 953
            ['name' => 'Viral Marketing'], // 954
            ['name' => 'Search Engine Marketing (SEM)'], // 955
            ['name' => 'Pay-Per-Click (PPC) Advertising'], // 956
            ['name' => 'Marketing Analytics'], // 957
            ['name' => 'Conversion Rate Optimization (CRO)'], // 958
            ['name' => 'Search Engine Optimization (SEO)'], // 959
            ['name' => 'Email List Management'], // 960
            ['name' => 'Marketing Automation'], // 961
            ['name' => 'Google Analytics'], // 962
            ['name' => 'Facebook Ads'], // 963
            ['name' => 'Instagram Ads'], // 964
            ['name' => 'LinkedIn Ads'], // 965
            ['name' => 'Snapchat Ads'], // 966
            ['name' => 'Pinterest Ads'], // 967
            ['name' => 'Twitter Ads'], // 968
            ['name' => 'Google AdWords'], // 969
            ['name' => 'Salesforce Marketing Cloud'], // 970
            ['name' => 'HubSpot'], // 971
            ['name' => 'Hootsuite'], // 972
            ['name' => 'Buffer'], // 973
            ['name' => 'Trello'], // 974
            ['name' => 'Asana'], // 975
            ['name' => 'Basecamp'], // 976
            ['name' => 'Monday.com'], // 977
            ['name' => 'ClickUp'], // 978
            ['name' => 'Slack'], // 979
            ['name' => 'Microsoft Teams'], // 980
            ['name' => 'Jira'], // 981
            ['name' => 'Confluence'], // 982
            ['name' => 'Notion'], // 983
            ['name' => 'Google Drive'], // 984
            ['name' => 'Dropbox'], // 985
            ['name' => 'Box'], // 986
            ['name' => 'OneDrive'], // 987
            ['name' => 'Google Docs'], // 988
            ['name' => 'Microsoft Word'], // 989
            ['name' => 'Excel'], // 990
            ['name' => 'Google Sheets'], // 991
            ['name' => 'Microsoft PowerPoint'], // 992
            ['name' => 'Canva'], // 993
            ['name' => 'Adobe Photoshop'], // 994
            ['name' => 'Adobe Illustrator'], // 995
            ['name' => 'InDesign'], // 996
            ['name' => 'Premiere Pro'], // 997
            ['name' => 'Final Cut Pro'], // 998
            ['name' => 'Adobe After Effects'], // 999
            ['name' => 'Video Editing'], // 1000
            ['name' => 'Oil Painting'], // 1001
            ['name' => 'Watercolor Painting'], // 1002
            ['name' => 'Acrylic Painting'], // 1003
            ['name' => 'Charcoal Drawing'], // 1004
            ['name' => 'Pencil Sketching'], // 1005
            ['name' => 'Sculpting'], // 1006
            ['name' => 'Pottery Making'], // 1007
            ['name' => 'Wood Carving'], // 1008
            ['name' => 'Metalworking'], // 1009
            ['name' => 'Leather Crafting'], // 1010
            ['name' => 'Jewelry Making'], // 1011
            ['name' => 'Floral Arrangement'], // 1012
            ['name' => 'Fashion Design'], // 1013
            ['name' => 'Sewing'], // 1014
            ['name' => 'Embroidery'], // 1015
            ['name' => 'Knitting'], // 1016
            ['name' => 'Crocheting'], // 1017
            ['name' => 'Quilting'], // 1018
            ['name' => 'Origami'], // 1019
            ['name' => 'Scrapbooking'], // 1020
            ['name' => 'Stamp Collecting'], // 1021
            ['name' => 'Comic Book Collecting'], // 1022
            ['name' => 'Antique Collecting'], // 1023
            ['name' => 'Calligraphy'], // 1024
            ['name' => 'Tattoo Art'], // 1025
            ['name' => 'Graffiti Art'], // 1026
            ['name' => 'Voice Acting'], // 1027
            ['name' => 'Singing'], // 1028
            ['name' => 'Songwriting'], // 1029
            ['name' => 'Music Composition'], // 1030
            ['name' => 'Guitar Playing'], // 1031
            ['name' => 'Piano Playing'], // 1032
            ['name' => 'Violin Playing'], // 1033
            ['name' => 'Drumming'], // 1034
            ['name' => 'DJing'], // 1035
            ['name' => 'Music Production'], // 1036
            ['name' => 'Dance Choreography'], // 1037
            ['name' => 'Ballet Dancing'], // 1038
            ['name' => 'Hip-Hop Dancing'], // 1039
            ['name' => 'Contemporary Dancing'], // 1040
            ['name' => 'Salsa Dancing'], // 1041
            ['name' => 'Ballroom Dancing'], // 1042
            ['name' => 'Stand-Up Comedy'], // 1043
            ['name' => 'Improvisation'], // 1044
            ['name' => 'Mime Performance'], // 1045
            ['name' => 'Physical Comedy'], // 1046
            ['name' => 'Puppetry'], // 1047
            ['name' => 'Magician'], // 1048
            ['name' => 'Juggling'], // 1049
            ['name' => 'Circus Skills'], // 1050
            ['name' => 'Stage Acting'], // 1051
            ['name' => 'Film Acting'], // 1052
            ['name' => 'Stunt Performing'], // 1053
            ['name' => 'Public Speaking'], // 1054
            ['name' => 'Debate'], // 1055
            ['name' => 'Motivational Speaking'], // 1056
            ['name' => 'Personal Training'], // 1057
            ['name' => 'Yoga Teaching'], // 1058
            ['name' => 'Pilates Instruction'], // 1059
            ['name' => 'Aerobics Coaching'], // 1060
            ['name' => 'Weightlifting'], // 1061
            ['name' => 'Boxing'], // 1062
            ['name' => 'Martial Arts'], // 1063
            ['name' => 'Swimming'], // 1064
            ['name' => 'Skiing'], // 1065
            ['name' => 'Snowboarding'], // 1066
            ['name' => 'Rock Climbing'], // 1067
            ['name' => 'Hiking'], // 1068
            ['name' => 'Camping'], // 1069
            ['name' => 'Fishing'], // 1070
            ['name' => 'Bird Watching'], // 1071
            ['name' => 'Wildlife Photography'], // 1072
            ['name' => 'Pet Grooming'], // 1073
            ['name' => 'Dog Training'], // 1074
            ['name' => 'Animal Care'], // 1075
            ['name' => 'Gardening'], // 1076
            ['name' => 'Bonsai Cultivation'], // 1077
            ['name' => 'Landscape Design'], // 1078
            ['name' => 'Vegetable Gardening'], // 1079
            ['name' => 'Beekeeping'], // 1080
            ['name' => 'Sustainable Farming'], // 1081
            ['name' => 'Vineyard Management'], // 1082
            ['name' => 'Winemaking'], // 1083
            ['name' => 'Baking'], // 1084
            ['name' => 'Cake Decorating'], // 1085
            ['name' => 'Pastry Making'], // 1086
            ['name' => 'Bread Making'], // 1087
            ['name' => 'Chocolate Making'], // 1088
            ['name' => 'Culinary Arts'], // 1089
            ['name' => 'Butchery'], // 1090
            ['name' => 'Brewing'], // 1091
            ['name' => 'Mixology'], // 1092
            ['name' => 'Coffee Roasting'], // 1093
            ['name' => 'Food Presentation'], // 1094
            ['name' => 'Recipe Development'], // 1095
            ['name' => 'Nutrition'], // 1096
            ['name' => 'Diet Planning'], // 1097
            ['name' => 'Event Hosting'], // 1098
            ['name' => 'Bartending'], // 1099
            ['name' => 'Wedding Planning'], // 1100
            ['name' => 'Interior Decorating'], // 1101
            ['name' => 'Home Staging'], // 1102
            ['name' => 'Real Estate Staging'], // 1103
            ['name' => 'Furniture Design'], // 1104
            ['name' => 'Cabinet Making'], // 1105
            ['name' => 'Architecture'], // 1106
            ['name' => 'Home Renovation'], // 1107
            ['name' => 'Landscaping'], // 1108
            ['name' => 'Tile Setting'], // 1109
            ['name' => 'Masonry'], // 1110
            ['name' => 'Plumbing'], // 1111
            ['name' => 'Electric Wiring'], // 1112
            ['name' => 'Roofing'], // 1113
            ['name' => 'Carpentry'], // 1114
            ['name' => 'Auto Mechanics'], // 1115
            ['name' => 'Bike Repair'], // 1116
            ['name' => 'Boat Repair'], // 1117
            ['name' => 'Furniture Repair'], // 1118
            ['name' => 'Upholstery'], // 1119
            ['name' => 'Watch Repair'], // 1120
            ['name' => 'Shoe Repair'], // 1121
            ['name' => 'Tailoring'], // 1122
            ['name' => 'Laundry Services'], // 1123
            ['name' => 'Housekeeping'], // 1124
            ['name' => 'Pet Sitting'], // 1125
            ['name' => 'Elderly Care'], // 1126
            ['name' => 'Child Care'], // 1127
            ['name' => 'Counseling'], // 1128
            ['name' => 'Social Work'], // 1129
            ['name' => 'Community Organizing'], // 1130
            ['name' => 'Charity Fundraising'], // 1131
            ['name' => 'Public Health'], // 1132
            ['name' => 'Crisis Intervention'], // 1133
            ['name' => 'Cultural Preservation'], // 1134
            ['name' => 'Tour Guiding'], // 1135
            ['name' => 'Travel Planning'], // 1136
            ['name' => 'Language Interpretation'], // 1137
            ['name' => 'Sign Language'], // 1138
            ['name' => 'Anthropology'], // 1139
            ['name' => 'Archaeology'], // 1140
            ['name' => 'Historical Research'], // 1141
            ['name' => 'Genealogy'], // 1142
            ['name' => 'Museum Curation'], // 1143
            ['name' => 'Botany'], // 1144
            ['name' => 'Astronomy'], // 1145
            ['name' => 'Meteorology'], // 1146
            ['name' => 'Geology'], // 1147
            ['name' => 'Paleontology'], // 1148
            ['name' => 'Marine Biology'], // 1149
            ['name' => 'Wildlife Conservation'], // 1150
            ['name' => 'Environmental Science'], // 1151
            ['name' => 'Zoology'], // 1152
            ['name' => 'Sociology'], // 1153
            ['name' => 'Psychology'], // 1154
            ['name' => 'Philosophy'], // 1155
            ['name' => 'Poetry Writing'], // 1156
            ['name' => 'Creative Writing'], // 1157
            ['name' => 'Storytelling'], // 1158
            ['name' => 'Journalism'], // 1159
            ['name' => 'Speech Writing'], // 1160
            ['name' => 'Book Publishing'], // 1161
            ['name' => 'Editing'], // 1162
            ['name' => 'Proofreading'], // 1163
            ['name' => 'Copywriting'], // 1164
            ['name' => 'Screenwriting'], // 1165
            ['name' => 'Bookbinding'], // 1166
            ['name' => 'Library Management'], // 1167
            ['name' => 'Film Criticism'], // 1168
            ['name' => 'Art Criticism'], // 1169
            ['name' => 'Culinary Criticism'], // 1170
            ['name' => 'Wine Tasting'], // 1171
            ['name' => 'Tea Tasting'], // 1172
            ['name' => 'Fashion Modeling'], // 1173
            ['name' => 'Makeup Artistry'], // 1174
            ['name' => 'Hair Styling'], // 1175
            ['name' => 'Personal Styling'], // 1176
            ['name' => 'Bodybuilding'], // 1177
            ['name' => 'Sports Coaching'], // 1178
            ['name' => 'Golf Playing'], // 1179
            ['name' => 'Tennis Playing'], // 1180
            ['name' => 'Soccer Playing'], // 1181
            ['name' => 'Basketball Playing'], // 1182
            ['name' => 'Baseball Playing'], // 1183
            ['name' => 'Hockey Playing'], // 1184
            ['name' => 'Volleyball Playing'], // 1185
            ['name' => 'Table Tennis Playing'], // 1186
            ['name' => 'Chess Playing'], // 1187
            ['name' => 'Scrabble Playing'], // 1188
            ['name' => 'Poker Playing'], // 1189
            ['name' => 'Bridge Playing'], // 1190
            ['name' => 'Fantasy Sports Management'], // 1191
            ['name' => 'Horse Riding'], // 1192
            ['name' => 'Archery'], // 1193
            ['name' => 'Hunting'], // 1194
            ['name' => 'Survival Skills'], // 1195
            ['name' => 'Orienteering'], // 1196
            ['name' => 'Scuba Diving'], // 1197
            ['name' => 'Sailing'], // 1198
            ['name' => 'Surfing'], // 1199
            ['name' => 'Parasailing'], // 1200
        ];

        DB::table('skills')->insert($skills);
    }
}
