import { Airplay, BarChart, Box, Calendar, CheckSquare, Clock, Cloud, Command, Database, Edit, File, FolderPlus, GitPullRequest, Heart, HelpCircle, Home, Image, Layers, Layout, List, Mail, Map, MessageCircle, Package, Radio, Search, Server, ShoppingBag, Sliders, Sunrise, UserCheck, Users, Zap } from "react-feather";

export const MENUITEMS = [
  {
    menutitle: "General",
    menucontent: "Dashboards,Widgets",
    Items: [
      {
        title: "Dashboard",
        icon: Home,
        type: "sub",
        active: false,
        children: [
          { path: ``, title: "Default", type: "link" },
          { path: `about`, title: "Ecommerce", type: "link" },
        ],
      },
      {
        title: "Widgets",
        icon: Airplay,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/widgets/general`, title: "General", type: "link" },
          { path: `http://127.0.0.1:8000/widgets/chart`, title: "Chart", type: "link" },
        ],
      },
      {
        title: "Page layout",
        icon: Layout,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/page-layout/footer-light`, title: "Footer Light", type: "link" },
          { path: `http://127.0.0.1:8000/page-layout/footer-dark`, title: "Footer Dark", type: "link" },
          { path: `http://127.0.0.1:8000/page-layout/footer-fixed`, title: "Footer Fixed", type: "link" },
        ],
      },
    ],
  },
  {
    menutitle: "Components",
    Items: [
      {
        title: "Ui Kits",
        icon: Box,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/ui-kits/typography`, type: "link", title: "Typography" },
          { path: `http://127.0.0.1:8000/ui-kits/avatars`, type: "link", title: "Avatars" },
          { path: `http://127.0.0.1:8000/ui-kits/helper-classes`, type: "link", title: "Helper Classes" },
          { path: `http://127.0.0.1:8000/ui-kits/grid`, type: "link", title: "Grid" },
          { path: `http://127.0.0.1:8000/ui-kits/tag-pills`, type: "link", title: "Tag & Pills" },
          { path: `http://127.0.0.1:8000/ui-kits/progress`, type: "link", title: "Progress" },
          { path: `http://127.0.0.1:8000/ui-kits/modal`, type: "link", title: "Modal" },
          { path: `http://127.0.0.1:8000/ui-kits/alert`, type: "link", title: "Alert" },
          { path: `http://127.0.0.1:8000/ui-kits/popover`, type: "link", title: "Popover" },
          { path: `http://127.0.0.1:8000/ui-kits/tooltip`, type: "link", title: "Tooltip" },
          { path: `http://127.0.0.1:8000/ui-kits/spinners`, type: "link", title: "Spinners" },
          { path: `http://127.0.0.1:8000/ui-kits/dropdown`, type: "link", title: "Dropdown" },
          { path: `http://127.0.0.1:8000/ui-kits/accordion`, type: "link", title: "Accordion" },
          {
            type: "sub",
            title: "Tabs",
            children: [
              { path: `http://127.0.0.1:8000/ui-kits/tab-bootstrap`, type: "link", title: "Tab Bootstrap" },
              { path: `http://127.0.0.1:8000/ui-kits/line-tabs`, type: "link", title: "Line Tabs" },
            ],
          },
          { path: `http://127.0.0.1:8000/ui-kits/navs`, type: "link", title: "Navs" },
          { path: `http://127.0.0.1:8000/ui-kits/shadow`, type: "link", title: "Shadow" },
          { path: `http://127.0.0.1:8000/ui-kits/lists`, type: "link", title: "Lists" },
        ],
      },
      {
        title: "Bonus Ui",
        icon: FolderPlus,
        type: "sub",
        badge1: true,
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/bonus-ui/scrollable`, title: "Scrollable ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/tree-view`, title: "Tree View ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/bootstrap-notify`, title: "Bootstrap Notify ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/rating`, title: "Rating", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/dropzone`, title: "Dropzone", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/tour`, title: "Tour ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/sweet-alert`, title: "SweetAlert ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/carousel`, title: "Owl Carousel", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/ribbons`, title: "Ribbons", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/pagination`, title: "Pagination", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/steps`, title: "Steps", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/breadcrumb`, title: "Breadcrumb ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/rangeSlider`, title: "Range Slider ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/imageCropper`, title: "Image Cropper ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/stickyNotes`, title: "Sticky ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/dragNDropComp`, title: "Drag and Drop ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/image-upload`, title: "Upload", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/card/basicCards`, title: "Basic Card ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/card/creativeCards`, title: "Creative Card ", type: "link" },
          { path: `http://127.0.0.1:8000/bonus-ui/card/tabCard`, title: "Tabbed Card ", type: "link" },
          // { path: `http://127.0.0.1:8000/bonus-ui/card/draggingCards`, title: 'Draggable Card', type: 'link' },
          { path: `http://127.0.0.1:8000/bonus-ui/timelines/timeline1`, title: "Timeline", type: "link" },
        ],
      },
      {
        title: "Icons",
        icon: Command,
        path: `http://127.0.0.1:8000/icons/flagIcons`,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/icons/flagIcons`, title: "Flag Icon", type: "link" },
          { path: `http://127.0.0.1:8000/icons/fontAwsomeIcon`, title: "Fontawesome Icon ", type: "link" },
          { path: `http://127.0.0.1:8000/icons/icoIcons`, title: "Ico Icon ", type: "link" },
          { path: `http://127.0.0.1:8000/icons/themifyIcons`, title: "Themify Icon ", type: "link" },
          { path: `http://127.0.0.1:8000/icons/featherIcons`, title: "Feather Icon ", type: "link" },
          { path: `http://127.0.0.1:8000/icons/weatherIcons`, title: "Whether Icon ", type: "link" },
        ],
      },
      {
        title: "Buttons",
        icon: Cloud,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/buttons/default-btn`, title: "Default Style ", type: "link" },
          { path: `http://127.0.0.1:8000/buttons/flatBtn`, title: "Flat Style", type: "link" },
          { path: `http://127.0.0.1:8000/buttons/edgeBtn`, title: "Edge Style", type: "link" },
          { path: `http://127.0.0.1:8000/buttons/raisedBtn`, title: "Raised Style", type: "link" },
          { path: `http://127.0.0.1:8000/buttons/groupBtn`, title: "Button Group", type: "link" },
        ],
      },
      {
        title: "Charts",
        icon: BarChart,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/charts/apexCharts`, type: "link", title: "Apex Chart" },
          { path: `http://127.0.0.1:8000/charts/googleChart`, type: "link", title: "Google Chart" },
          { path: `http://127.0.0.1:8000/charts/chartJs`, type: "link", title: "Chartjs Chart" },
        ],
      },
    ],
  },
  {
    menutitle: "Forms",
    Items: [
      {
        title: " Form Controls ",
        icon: Sliders,
        type: "sub",
        children: [
          { title: "Form Validation", type: "link", path: `http://127.0.0.1:8000/forms/formValidation` },
          { title: "Basic Input", type: "link", path: `http://127.0.0.1:8000/forms/baseInput` },
          { title: "Checkbox & Radio", type: "link", path: `http://127.0.0.1:8000/forms/radio-checkbox` },
          { title: "Input Groups", type: "link", path: `http://127.0.0.1:8000/forms/inputGroup` },
          { title: "Mega Option", type: "link", path: `http://127.0.0.1:8000/forms/megaOptions` },
        ],
      },
      {
        title: "Form Widgets",
        icon: Package,
        type: "sub",
        children: [
          { title: "Datepicker", type: "link", path: `http://127.0.0.1:8000/form-widget/datepicker` },
          { title: "Typeahead", type: "link", path: `http://127.0.0.1:8000/form-widget/typeahead` },
          { title: "Date Rangepicker", type: "link", path: `http://127.0.0.1:8000/form-widget/rangepicker` },
          { title: "TouchSpin", type: "link", path: `http://127.0.0.1:8000/form-widget/touchspin` },
          { title: "Select 2", type: "link", path: `http://127.0.0.1:8000/form-widget/select2` },
          { title: "Switch", type: "link", path: `http://127.0.0.1:8000/form-widget/switch` },
          { title: "ClipBoard", type: "link", path: `http://127.0.0.1:8000/form-widget/clipBoard` },
        ],
      },
      {
        title: "Form Layout",
        icon: Layout,
        type: "sub",
        children: [
          { path: `http://127.0.0.1:8000/form-layout/formDefault`, title: "Form Default", type: "link" },
          { path: `http://127.0.0.1:8000/form-layout/formWizard`, title: "Form Wizard", type: "link" },
        ],
      },
    ],
  },
  {
    menutitle: "Table",
    Items: [
      {
        title: "Bootstrap Table ",
        icon: Server,
        type: "sub",
        children: [
          { title: "Basic Table", type: "link", path: `http://127.0.0.1:8000/table/basic` },
          { title: "Sizing Table", type: "link", path: `http://127.0.0.1:8000/table/sizing` },
          { title: "Border Table", type: "link", path: `http://127.0.0.1:8000/table/border` },
          { title: "Styling Table", type: "link", path: `http://127.0.0.1:8000/table/styling` },
        ],
      },
      {
        title: "Data Tables",
        icon: Database,
        type: "link",
        path: `http://127.0.0.1:8000/table/data-table`,
      },
    ],
  },
  {
    menutitle: "Applications",
    Items: [
      {
        title: "Project",
        icon: Box,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/project/project-list`, type: "link", title: "Project List" },
          { path: `http://127.0.0.1:8000/app/project/new-project`, type: "link", title: "Create New" },
        ],
      },
      {
        title: "Ecommerce",
        icon: ShoppingBag,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/ecommerce/product`, title: "Product", type: "link" },
          { path: `http://127.0.0.1:8000/app/ecommerce/product-page/1`, title: "Product Page", type: "link" },
          { path: `http://127.0.0.1:8000/app/ecommerce/product-list`, title: "Product List", type: "link" },
          { path: `http://127.0.0.1:8000/app/ecommerce/payment-details`, title: "Payment Detail", type: "link" },
          { path: `http://127.0.0.1:8000/app/ecommerce/orderhistory`, title: "Order History", type: "link" },
          { path: `http://127.0.0.1:8000/app/ecommerce/pricing`, title: "Pricing", type: "link" },
        ],
      },
      {
        title: "Users",
        icon: Users,
        path: `http://127.0.0.1:8000/app/users/userProfile`,
        type: "sub",
        bookmark: true,
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/users/userProfile`, type: "link", title: "Users Profile " },
          { path: `http://127.0.0.1:8000/app/users/userEdit`, type: "link", title: "Users Edit" },
          { path: `http://127.0.0.1:8000/app/users/userCards`, type: "link", title: "Users Cards" },
        ],
      },
      {
        title: "Calender",
        icon: Calendar,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/calendar/basic-calendar`, bookmark: true, type: "link", title: "Calender" },
          { path: `http://127.0.0.1:8000/app/calendar/draggable-calendar`, type: "link", title: "Draggable" },
        ],
      },
      {
        icon: List,
        type: "sub",
        title: "Contacts",
        children: [{ path: `http://127.0.0.1:8000/app/contact`, type: "link", title: "Contact" }],
      },
      {
        bookmark: true,
        icon: MessageCircle,
        title: "Chat",
        type: "sub",
        children: [
          { path: `http://127.0.0.1:8000/app/chat-app`, type: "link", title: "Chat-app" },
          { path: `http://127.0.0.1:8000/app/chat-video-app`, type: "link", title: "Chat-video-app" },
        ],
      },
      {
        icon: Mail,
        title: "Email-app",
        type: "sub",
        children: [
          { path: `http://127.0.0.1:8000/app/email/mailbox`, type: "link", title: "Mail Box" },
          { path: `http://127.0.0.1:8000/app/email/readmail`, type: "link", title: "Read Mail" },
          { path: `http://127.0.0.1:8000/app/email/compose`, type: "link", title: "Compose" },
        ],
      },
      { path: `http://127.0.0.1:8000/app/file-manager`, icon: GitPullRequest, title: "File Manager", type: "link" },
      { path: `http://127.0.0.1:8000/app/bookmark`, icon: Heart, type: "link", title: "Bookmark" },
      { path: `http://127.0.0.1:8000/app/task`, icon: CheckSquare, type: "link", title: "Task" },
      { path: `http://127.0.0.1:8000/app/social-app`, bookmark: true, icon: Zap, type: "link", title: "Social App" },
      { path: `http://127.0.0.1:8000/app/todo`, icon: Clock, type: "link", title: "To-Do" },
      { path: `http://127.0.0.1:8000/app/search-result`, icon: Search, type: "link", title: "Seach Result" },
    ],
  },
  {
    menutitle: "Pages",
    Items: [
      {
        title: "Sample Page",
        icon: File,
        type: "link",
        path: `http://127.0.0.1:8000/pages/sample-page`,
      },
      {
        title: "Others",
        icon: Layers,
        type: "sub",
        children: [
          {
            title: "Error Pages",
            type: "sub",
            children: [
              { title: "Error Page 1", type: "link", path: `http://127.0.0.1:8000/pages/error/error-page1` },
              { title: "Error Page 2", type: "link", path: `http://127.0.0.1:8000/pages/error/error-page2` },
              { title: "Error Page 3", type: "link", path: `http://127.0.0.1:8000/pages/error/error-page3` },
              { title: "Error Page 4", type: "link", path: `http://127.0.0.1:8000/pages/error/error-page4` },
            ],
          },
          {
            title: "Authentication",
            type: "sub",
            children: [
              { title: "Login Simple", type: "link", path: `http://127.0.0.1:8000/pages/authentication/login-simple` },
              { title: "Login with bg image", type: "link", path: `http://127.0.0.1:8000/pages/authentication/login-bg-img` },
              { title: "Login with image two", type: "link", path: `http://127.0.0.1:8000/pages/authentication/login-img` },
              { title: "Login with validation", type: "link", path: `http://127.0.0.1:8000/pages/authentication/login-validation` },
              { title: "Login with tooltip", type: "link", path: `http://127.0.0.1:8000/pages/authentication/login-tooltip` },
              { title: "Login with sweetalert", type: "link", path: `http://127.0.0.1:8000/pages/authentication/login-sweetalert` },
              { title: "Register Simple", type: "link", path: `http://127.0.0.1:8000/pages/authentication/register-simple` },
              { title: "Register with Bg Image", type: "link", path: `http://127.0.0.1:8000/pages/authentication/register-bg-img` },
              { title: "Register with Bg Video", type: "link", path: `http://127.0.0.1:8000/pages/authentication/register-video` },
              { title: "Unloack User", type: "link", path: `http://127.0.0.1:8000/pages/authentication/unlock-user` },
              { title: "Forget Password", type: "link", path: `http://127.0.0.1:8000/pages/authentication/forget-pwd` },
              { title: "Creat Password", type: "link", path: `http://127.0.0.1:8000/pages/authentication/create-pwd` },
              { title: "Maintenance", type: "link", path: `http://127.0.0.1:8000/pages/authentication/maintenance` },
            ],
          },
          {
            title: "Coming Soon",
            type: "sub",
            children: [
              { title: "Coming Simple", type: "link", path: `http://127.0.0.1:8000/pages/coming/coming-simple` },
              { title: "Coming with Bg Video", type: "link", path: `http://127.0.0.1:8000/pages/coming/coming-bg-video` },
              { title: "Coming with bg Image", type: "link", path: `http://127.0.0.1:8000/pages/coming/coming-bg-img` },
            ],
          },
        ],
      },
    ],
  },
  {
    menutitle: "Miscellaneous",
    Items: [
      {
        title: "Gallery",
        icon: Image,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/gallery/imageGallery`, title: "Gallery Grid ", type: "link" },
          { path: `http://127.0.0.1:8000/app/gallery/imageWithDesc`, title: "Gallery Grid  Desc ", type: "link" },
          { path: `http://127.0.0.1:8000/app/gallery/mesonryGallery`, title: "Masonry Gallery", type: "link" },
          { path: `http://127.0.0.1:8000/app/gallery/mesonryDesc`, title: "Masonry With Desc", type: "link" },
          { path: `http://127.0.0.1:8000/app/gallery/imageHover`, title: "Hover Effect", type: "link" },
        ],
      },
      {
        title: "Blog",
        icon: Edit,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/blog/blogDetail`, title: "Blog Details", type: "link" },
          { path: `http://127.0.0.1:8000/app/blog/blogSingle`, title: "Blog Single", type: "link" },
          { path: `http://127.0.0.1:8000/app/blog/blogPost`, title: "Add Post", type: "link" },
        ],
      },
      {
        title: "Job Search",
        icon: UserCheck,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/jobSearch/cardView`, title: "Cards View", type: "link" },
          { path: `http://127.0.0.1:8000/app/jobSearch/job-list`, title: "List View", type: "link" },
          { path: `http://127.0.0.1:8000/app/jobSearch/job-detail`, title: "Job Details", type: "link" },
          { path: `http://127.0.0.1:8000/app/jobSearch/job-apply`, title: "Apply", type: "link" },
        ],
      },
      {
        title: "Learning",
        icon: Radio,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/learning/learning-list`, title: "Learning List", type: "link" },
          { path: `http://127.0.0.1:8000/app/learning/learning-detail`, title: "Detailed Course", type: "link" },
        ],
      },
      {
        title: "Maps",
        icon: Map,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/app/map/googleMap`, type: "link", title: "Google Maps " },
          { path: `http://127.0.0.1:8000/app/map/leaflet-map`, type: "link", title: "Leaflet Maps" },
        ],
      },
      {
        title: "Editor",
        icon: Edit,
        type: "sub",
        active: false,
        children: [
          { path: `http://127.0.0.1:8000/editor/ckEditor`, type: "link", title: "CK  Editor" },
          { path: `http://127.0.0.1:8000/editor/mdeEditor`, type: "link", title: "MDE Editor" },
          { path: `http://127.0.0.1:8000/editor/ace-code-editor`, type: "link", title: "ACE code Editor " },
        ],
      },

      { path: `http://127.0.0.1:8000/app/faq`, icon: HelpCircle, type: "link", active: false, title: "FAQ" },
      {
        icon: Sunrise,
        type: "sub",
        active: false,
        title: "Knowledgebase",
        children: [
          { path: `http://127.0.0.1:8000/app/knowledgebase`, title: "Knowledgebase", type: "link" },
          { path: `http://127.0.0.1:8000/app/knowledgebase-category`, title: "Knowledgebase Category", type: "link" },
          { path: `http://127.0.0.1:8000/app/knowledgebase-detail`, title: "Knowledgebase Detail", type: "link" },
        ],
      },
      { path: `http://127.0.0.1:8000/app/support-ticket`, icon: Users, type: "link", active: false, title: "Support Ticket" },
    ],
  },
];
