name: Laravel Deployment to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH connection to server
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PASSWORD }}

    # Step 3: Deploy code to server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          # Navigate to the project directory
          cd /var/www/html/erp

          # Pull the latest changes from the repository
          git pull origin main

          # Ensure correct permissions for Laravel
          chmod -R 775 storage bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache

          # Install/update dependencies
          composer install --no-dev --optimize-autoloader

          # Run database migrations
          php artisan migrate --force

          # Clear and cache configurations
          php artisan config:clear
          php artisan config:cache
          php artisan route:clear
          php artisan route:cache
          php artisan view:clear
          php artisan view:cache

          # Restart PHP to apply changes (if necessary)
          sudo service php8.2-fpm restart
        EOF
`